-- =========================================
-- MINDSHARE TRAINING DATA SEED - 100 RECORDS
-- =========================================
-- Realistic training data from various platforms for ML model training

-- Generate realistic mindshare training data with diverse content types and engagement patterns
INSERT INTO mindshare_training_data (
  "platformSource",
  "contentHash",
  "contentText",
  "contentImages",
  "engagementMetrics",
  "mindshareScore",
  "timestampPosted",
  "campaignContext",
  "scrapedAt"
) VALUES 

-- Cookie.fun Training Data (50 records)
('cookie.fun', 'cookie_001_hash', 'Just launched my gaming montage on @cookie_fun! 🎮 This new web3 gaming ecosystem is absolutely revolutionary. Who else is ready to earn while they play? #Web3Gaming #COOKIE', '{"hasImages": true, "imageCount": 1, "imageTypes": ["screenshot"]}', '{"likes": 1250, "retweets": 340, "replies": 89, "views": 12500, "engagementRate": 13.5}', 89.2, NOW() - INTERVAL '5 hours', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "video_promotion"}', NOW() - INTERVAL '4 hours'),

('cookie.fun', 'cookie_002_hash', 'GM Cookie fam! ☕ Today''s market analysis: $COOKIE showing strong support at $0.45. The gaming sector is heating up and we''re positioned perfectly 📈', NULL, '{"likes": 890, "retweets": 156, "replies": 67, "views": 8900, "engagementRate": 12.5}', 82.7, NOW() - INTERVAL '1 day', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "market_analysis"}', NOW() - INTERVAL '23 hours'),

('cookie.fun', 'cookie_003_hash', 'BREAKING: New partnership announced! 🚀 Cookie.fun x Major Gaming Studio. This changes everything for web3 gaming adoption. Thread below 🧵', '{"hasImages": true, "imageCount": 2, "imageTypes": ["infographic", "logo"]}', '{"likes": 2100, "retweets": 567, "replies": 234, "views": 21000, "engagementRate": 13.8}', 94.1, NOW() - INTERVAL '2 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "partnership_announcement"}', NOW() - INTERVAL '1 day 23 hours'),

('cookie.fun', 'cookie_004_hash', 'Unpopular opinion: Traditional gaming will be obsolete in 5 years. Web3 gaming with actual ownership and earning potential is the future. Fight me 💪 #Web3', NULL, '{"likes": 445, "retweets": 89, "replies": 156, "views": 4450, "engagementRate": 15.5}', 76.3, NOW() - INTERVAL '3 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "opinion"}', NOW() - INTERVAL '2 days 22 hours'),

('cookie.fun', 'cookie_005_hash', 'Tutorial Tuesday! 📚 How to maximize your $COOKIE earnings: 1) Complete daily quests 2) Participate in tournaments 3) Stake for bonus rewards 4) Refer friends. Simple but effective!', '{"hasImages": true, "imageCount": 1, "imageTypes": ["tutorial_graphic"]}', '{"likes": 678, "retweets": 123, "replies": 45, "views": 6780, "engagementRate": 12.5}', 85.9, NOW() - INTERVAL '4 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "tutorial"}', NOW() - INTERVAL '3 days 21 hours'),

('cookie.fun', 'cookie_006_hash', 'Web3 gaming just hit different today! 🎯 Earned 150 $COOKIE tokens in 2 hours just playing my favorite games. This is the future of entertainment! #PlayToEarn', '{"hasImages": true, "imageCount": 1, "imageTypes": ["earnings_screenshot"]}', '{"likes": 892, "retweets": 178, "replies": 56, "views": 8920, "engagementRate": 12.6}', 83.2, NOW() - INTERVAL '5 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "earnings_update"}', NOW() - INTERVAL '4 days 20 hours'),

('cookie.fun', 'cookie_007_hash', 'Hot take: Gaming will democratize crypto adoption. Why struggle with traditional investments when you can earn while playing? $COOKIE is leading this revolution 💪', NULL, '{"likes": 567, "retweets": 89, "replies": 134, "views": 5670, "engagementRate": 13.9}', 78.5, NOW() - INTERVAL '6 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "hot_take"}', NOW() - INTERVAL '5 days 19 hours'),

('cookie.fun', 'cookie_008_hash', 'Cookie gaming meme incoming! 📊 When the web3 game hits different and your wallet is suddenly full 🟢 *insert dancing crab gif* #CookieGaming #Web3Gaming', '{"hasImages": true, "imageCount": 1, "imageTypes": ["meme"]}', '{"likes": 1234, "retweets": 345, "replies": 67, "views": 12340, "engagementRate": 13.3}', 81.7, NOW() - INTERVAL '7 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "gaming_meme"}', NOW() - INTERVAL '6 days 18 hours'),

('cookie.fun', 'cookie_009_hash', 'Community spotlight! 🌟 Meet Sarah, who went from casual gamer to earning $500/month through Cookie.fun gaming ecosystem. Her strategy: diversify across 5 top games. Genius! 🧠', '{"hasImages": true, "imageCount": 2, "imageTypes": ["profile", "chart"]}', '{"likes": 756, "retweets": 145, "replies": 89, "views": 7560, "engagementRate": 13.1}', 84.9, NOW() - INTERVAL '8 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "community_spotlight"}', NOW() - INTERVAL '7 days 17 hours'),

('cookie.fun', 'cookie_010_hash', 'Chart analysis masterclass 📊 This $COOKIE setup is textbook perfect: - Higher lows forming - Volume increasing - RSI showing bullish divergence - Breaking resistance #CookieAnalysis #Web3Gaming', '{"hasImages": true, "imageCount": 2, "imageTypes": ["chart", "indicators"]}', '{"likes": 1234, "retweets": 278, "replies": 89, "views": 12340, "engagementRate": 12.9}', 87.6, NOW() - INTERVAL '9 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "chart_analysis"}', NOW() - INTERVAL '8 days 16 hours'),

('cookie.fun', 'cookie_011_hash', 'Pro tip: Always check the gaming metrics before investing! Look for: ✅ Active players ✅ Reasonable token economics ✅ Daily rewards ✅ No suspicious wallets #DYOR #CookieGaming', NULL, '{"likes": 890, "retweets": 156, "replies": 67, "views": 8900, "engagementRate": 12.5}', 85.3, NOW() - INTERVAL '10 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "educational_tip"}', NOW() - INTERVAL '9 days 15 hours'),

('cookie.fun', 'cookie_012_hash', 'NFT gaming is the next big wave! 🌊 Cookie.fun''s upcoming NFT marketplace will let you trade rare in-game items across multiple games. Beta starts next week! #NFTGaming', '{"hasImages": true, "imageCount": 3, "imageTypes": ["nft_preview", "marketplace_ui", "game_items"]}', '{"likes": 1456, "retweets": 367, "replies": 123, "views": 14560, "engagementRate": 13.4}', 88.9, NOW() - INTERVAL '11 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "nft_announcement"}', NOW() - INTERVAL '10 days 14 hours'),

('cookie.fun', 'cookie_013_hash', 'Governance proposal live! 🗳️ Should we increase daily $COOKIE rewards by 25%? Community vote ends in 48 hours. Your voice matters! Link in bio #CookieDAO', NULL, '{"likes": 678, "retweets": 234, "replies": 156, "views": 6780, "engagementRate": 15.8}', 79.4, NOW() - INTERVAL '12 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "governance"}', NOW() - INTERVAL '11 days 13 hours'),

('cookie.fun', 'cookie_014_hash', 'Weekend gaming session complete! 💪 Highlights: - 5 tournaments won - 200+ $COOKIE earned - 3 new rare items found - Made 10 new friends in guild chat. Best weekend ever!', '{"hasImages": true, "imageCount": 1, "imageTypes": ["gaming_stats"]}', '{"likes": 534, "retweets": 89, "replies": 67, "views": 5340, "engagementRate": 12.9}', 76.8, NOW() - INTERVAL '13 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "personal_update"}', NOW() - INTERVAL '12 days 12 hours'),

('cookie.fun', 'cookie_015_hash', 'Behind the scenes: Cookie.fun dev team working 24/7 on the mobile app! 📱 Cross-platform gaming is coming soon. Same games, same rewards, anywhere you go! #MobileGaming', '{"hasImages": true, "imageCount": 2, "imageTypes": ["dev_team", "mobile_mockup"]}', '{"likes": 987, "retweets": 245, "replies": 78, "views": 9870, "engagementRate": 13.2}', 85.1, NOW() - INTERVAL '14 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "development_update"}', NOW() - INTERVAL '13 days 11 hours'),

('cookie.fun', 'cookie_016_hash', 'Macro Monday: Gaming sector outperforming by 340% this quarter 📈 $COOKIE leading the charge with consistent utility and real-world adoption. Fundamentals > hype every time', NULL, '{"likes": 1123, "retweets": 289, "replies": 134, "views": 11230, "engagementRate": 13.8}', 89.6, NOW() - INTERVAL '15 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "macro_analysis"}', NOW() - INTERVAL '14 days 10 hours'),

('cookie.fun', 'cookie_017_hash', 'LIVE: Cookie.fun x Twitch integration demo! 🔴 Streamers can now earn $COOKIE while entertaining viewers. Real-time donations, subscriber rewards, gaming achievements - all on-chain!', '{"hasImages": true, "imageCount": 1, "imageTypes": ["twitch_integration"]}', '{"likes": 1567, "retweets": 445, "replies": 189, "views": 15670, "engagementRate": 14.1}', 91.3, NOW() - INTERVAL '16 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "live_demo"}', NOW() - INTERVAL '15 days 9 hours'),

('cookie.fun', 'cookie_018_hash', 'Community challenge: Design the next Cookie.fun game mode! 🎮 Winner gets 10,000 $COOKIE + implementation in the platform. Submissions open until Friday! #GameDesign', '{"hasImages": true, "imageCount": 1, "imageTypes": ["challenge_poster"]}', '{"likes": 823, "retweets": 267, "replies": 234, "views": 8230, "engagementRate": 16.1}', 82.7, NOW() - INTERVAL '17 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "community_challenge"}', NOW() - INTERVAL '16 days 8 hours'),

('cookie.fun', 'cookie_019_hash', 'Partnerships update: Cookie.fun now integrated with 15+ major gaming studios! 🤝 AAA titles joining the web3 gaming revolution. Big announcements coming next month!', NULL, '{"likes": 1345, "retweets": 378, "replies": 156, "views": 13450, "engagementRate": 13.9}', 93.2, NOW() - INTERVAL '18 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "partnership_update"}', NOW() - INTERVAL '17 days 7 hours'),

('cookie.fun', 'cookie_020_hash', 'Technical deep dive: How Cookie.fun''s cross-chain infrastructure enables seamless gaming across 5 different blockchains ⛓️ Thread below for the tech-savvy community! 🧵', '{"hasImages": true, "imageCount": 2, "imageTypes": ["technical_diagram", "blockchain_flow"]}', '{"likes": 756, "retweets": 189, "replies": 89, "views": 7560, "engagementRate": 13.7}', 87.4, NOW() - INTERVAL '19 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "technical_content"}', NOW() - INTERVAL '18 days 6 hours'),

('cookie.fun', 'cookie_021_hash', 'Player economics 101: How $COOKIE token creates sustainable gaming economies 💰 Inflation-resistant, utility-driven, player-governed. This is how gaming finance should work!', NULL, '{"likes": 892, "retweets": 234, "replies": 123, "views": 8920, "engagementRate": 14.0}', 84.8, NOW() - INTERVAL '20 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "tokenomics_education"}', NOW() - INTERVAL '19 days 5 hours'),

('cookie.fun', 'cookie_022_hash', 'Esports announcement! 🏆 Cookie.fun organizing the first-ever web3 gaming championship. $100k prize pool in $COOKIE tokens. Registration opens Monday! #CookieChampionship', '{"hasImages": true, "imageCount": 1, "imageTypes": ["championship_poster"]}', '{"likes": 2134, "retweets": 567, "replies": 289, "views": 21340, "engagementRate": 14.2}', 95.1, NOW() - INTERVAL '21 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "esports_announcement"}', NOW() - INTERVAL '20 days 4 hours'),

('cookie.fun', 'cookie_023_hash', 'Security first: Cookie.fun smart contracts audited by 3 independent firms ✅ Bug bounty program launched with $50k rewards. Your funds and gaming progress are safe with us! #Security', NULL, '{"likes": 645, "retweets": 156, "replies": 67, "views": 6450, "engagementRate": 13.5}', 81.2, NOW() - INTERVAL '22 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "security_update"}', NOW() - INTERVAL '21 days 3 hours'),

('cookie.fun', 'cookie_024_hash', 'Developer spotlight: Meet Alex, lead engineer behind Cookie.fun''s lightning-fast transaction system ⚡ From idea to 50ms transaction times - innovation never stops!', '{"hasImages": true, "imageCount": 2, "imageTypes": ["developer_profile", "performance_metrics"]}', '{"likes": 534, "retweets": 123, "replies": 89, "views": 5340, "engagementRate": 14.0}', 78.9, NOW() - INTERVAL '23 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "team_spotlight"}', NOW() - INTERVAL '22 days 2 hours'),

('cookie.fun', 'cookie_025_hash', 'Sustainability matters: Cookie.fun is carbon-negative! 🌱 Partnering with environmental orgs to offset 150% of our blockchain footprint. Gaming for a better planet! #GreenGaming', '{"hasImages": true, "imageCount": 1, "imageTypes": ["sustainability_infographic"]}', '{"likes": 789, "retweets": 234, "replies": 134, "views": 7890, "engagementRate": 14.6}', 83.7, NOW() - INTERVAL '24 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "sustainability"}', NOW() - INTERVAL '23 days 1 hour'),

-- Additional Cookie.fun content (25 more records)
('cookie.fun', 'cookie_026_hash', 'Flash sale alert! 🚨 Premium gaming passes 50% off for the next 24 hours. Unlock exclusive games, double rewards, and VIP tournaments. Limited time only! #CookieSale', NULL, '{"likes": 1456, "retweets": 389, "replies": 167, "views": 14560, "engagementRate": 13.8}', 86.4, NOW() - INTERVAL '25 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "flash_sale"}', NOW() - INTERVAL '24 days'),

('cookie.fun', 'cookie_027_hash', 'AMA recap: CEO announces Cookie.fun 2.0 roadmap! 🗺️ - VR gaming integration - AI-powered matchmaking - Social gaming features - Cross-platform avatars. 2024 is going to be HUGE!', '{"hasImages": true, "imageCount": 1, "imageTypes": ["roadmap_graphic"]}', '{"likes": 1789, "retweets": 456, "replies": 234, "views": 17890, "engagementRate": 13.9}', 92.8, NOW() - INTERVAL '26 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "ama_recap"}', NOW() - INTERVAL '25 days'),

('cookie.fun', 'cookie_028_hash', 'Guild wars season 3 begins! ⚔️ 50 guilds competing for the ultimate prize: 25,000 $COOKIE + custom guild NFTs. May the best gamers win! #GuildWars', '{"hasImages": true, "imageCount": 2, "imageTypes": ["guild_war_banner", "prize_showcase"]}', '{"likes": 1234, "retweets": 345, "replies": 156, "views": 12340, "engagementRate": 14.1}', 88.2, NOW() - INTERVAL '27 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "guild_wars"}', NOW() - INTERVAL '26 days'),

('cookie.fun', 'cookie_029_hash', 'Innovation spotlight: Cookie.fun''s new AI companion learns your gaming style and suggests optimal strategies! 🤖 Personal gaming coach built into every game. The future is here!', NULL, '{"likes": 987, "retweets": 267, "replies": 123, "views": 9870, "engagementRate": 14.0}', 89.7, NOW() - INTERVAL '28 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "ai_feature"}', NOW() - INTERVAL '27 days'),

('cookie.fun', 'cookie_030_hash', 'Student spotlight: 16-year-old gamer pays for college tuition through Cookie.fun earnings! 🎓 $COOKIE providing real financial opportunities for dedicated players worldwide. #LifeChanger', '{"hasImages": true, "imageCount": 1, "imageTypes": ["student_success_story"]}', '{"likes": 2345, "retweets": 678, "replies": 345, "views": 23450, "engagementRate": 14.5}', 94.3, NOW() - INTERVAL '29 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "success_story"}', NOW() - INTERVAL '28 days'),

('cookie.fun', 'cookie_031_hash', 'Cross-game asset transfer now live! 🔄 Use your legendary sword from Fantasy Quest in Space Warriors. True digital ownership across our entire gaming ecosystem! #TrueOwnership', '{"hasImages": true, "imageCount": 2, "imageTypes": ["asset_transfer_demo", "cross_game_items"]}', '{"likes": 1567, "retweets": 423, "replies": 189, "views": 15670, "engagementRate": 14.0}', 90.5, NOW() - INTERVAL '30 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "cross_game_feature"}', NOW() - INTERVAL '29 days'),

('cookie.fun', 'cookie_032_hash', 'Streaming rewards program launched! 📹 Content creators earn $COOKIE for every hour streamed + bonus for viewer engagement. Turn your passion into passive income! #StreamToEarn', NULL, '{"likes": 1123, "retweets": 334, "replies": 145, "views": 11230, "engagementRate": 14.3}', 87.1, NOW() - INTERVAL '31 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "streaming_program"}', NOW() - INTERVAL '30 days'),

('cookie.fun', 'cookie_033_hash', 'Community governance in action! 🗳️ Players voted to implement "Casual Friday" - 2x rewards every Friday for stress-free gaming. Democracy wins again! #CookieDAO', '{"hasImages": true, "imageCount": 1, "imageTypes": ["governance_results"]}', '{"likes": 892, "retweets": 234, "replies": 167, "views": 8920, "engagementRate": 14.5}', 83.9, NOW() - INTERVAL '32 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "governance_results"}', NOW() - INTERVAL '31 days'),

('cookie.fun', 'cookie_034_hash', 'Technical achievement unlocked! 🔓 Cookie.fun processes 1 million transactions per day with 99.9% uptime. Scalability at its finest! #TechExcellence', NULL, '{"likes": 756, "retweets": 189, "replies": 89, "views": 7560, "engagementRate": 13.6}', 85.8, NOW() - INTERVAL '33 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "technical_milestone"}', NOW() - INTERVAL '32 days'),

('cookie.fun', 'cookie_035_hash', 'Regional expansion: Cookie.fun now supports 25+ languages! 🌍 Gaming knows no borders. Welcome our new players from Asia, Europe, and Latin America! #GlobalGaming', '{"hasImages": true, "imageCount": 1, "imageTypes": ["global_map_coverage"]}', '{"likes": 1345, "retweets": 378, "replies": 234, "views": 13450, "engagementRate": 14.6}', 88.7, NOW() - INTERVAL '34 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "global_expansion"}', NOW() - INTERVAL '33 days'),

('cookie.fun', 'cookie_036_hash', 'Education initiative: Cookie.fun partners with universities to teach blockchain gaming development! 🎓 Next generation of developers learning on our platform. #Education', NULL, '{"likes": 678, "retweets": 156, "replies": 123, "views": 6780, "engagementRate": 14.1}', 82.3, NOW() - INTERVAL '35 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "education_initiative"}', NOW() - INTERVAL '34 days'),

('cookie.fun', 'cookie_037_hash', 'Charity drive success! 💝 Cookie.fun community raised $50k for children''s hospitals through in-game purchases. Gaming for good - thank you amazing community! #GamingForGood', '{"hasImages": true, "imageCount": 2, "imageTypes": ["charity_total", "hospital_visit"]}', '{"likes": 2134, "retweets": 567, "replies": 289, "views": 21340, "engagementRate": 15.0}', 91.4, NOW() - INTERVAL '36 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "charity_success"}', NOW() - INTERVAL '35 days'),

('cookie.fun', 'cookie_038_hash', 'API launch: Developers can now build on Cookie.fun infrastructure! 🔧 Create custom games, integrate existing projects, access our player base. Ecosystem growth starts now! #APILaunch', NULL, '{"likes": 945, "retweets": 267, "replies": 134, "views": 9450, "engagementRate": 14.2}', 86.9, NOW() - INTERVAL '37 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "api_launch"}', NOW() - INTERVAL '36 days'),

('cookie.fun', 'cookie_039_hash', 'Player milestone: Cookie.fun hits 1 million registered players! 🎉 From 0 to 1M in 18 months. Thank you to every single player who believed in the vision! #1MillionStrong', '{"hasImages": true, "imageCount": 1, "imageTypes": ["milestone_celebration"]}', '{"likes": 3456, "retweets": 789, "replies": 456, "views": 34560, "engagementRate": 14.8}', 96.2, NOW() - INTERVAL '38 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "player_milestone"}', NOW() - INTERVAL '37 days'),

('cookie.fun', 'cookie_040_hash', 'Accessibility update: Cookie.fun now supports players with disabilities! ♿ Voice commands, colorblind-friendly UI, motor accessibility options. Gaming is for everyone! #Accessibility', NULL, '{"likes": 1567, "retweets": 445, "replies": 234, "views": 15670, "engagementRate": 14.3}', 88.1, NOW() - INTERVAL '39 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "accessibility_update"}', NOW() - INTERVAL '38 days'),

('cookie.fun', 'cookie_041_hash', 'Economic report: $COOKIE token holders earned $2.3M in rewards last quarter! 💰 Real value distribution to real players. This is how tokenomics should work! #EconomicReport', '{"hasImages": true, "imageCount": 1, "imageTypes": ["economic_infographic"]}', '{"likes": 1789, "retweets": 456, "replies": 178, "views": 17890, "engagementRate": 13.6}', 93.7, NOW() - INTERVAL '40 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "economic_report"}', NOW() - INTERVAL '39 days'),

('cookie.fun', 'cookie_042_hash', 'Innovation lab: Cookie.fun experimenting with holographic gaming displays! 📡 The future of immersive gaming starts in our R&D department. Sneak peek coming soon! #Innovation', NULL, '{"likes": 1234, "retweets": 345, "replies": 167, "views": 12340, "engagementRate": 14.1}', 89.8, NOW() - INTERVAL '41 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "innovation_preview"}', NOW() - INTERVAL '40 days'),

('cookie.fun', 'cookie_043_hash', 'Seasonal event: Winter Wonderland gaming festival! ❄️ Special holiday games, festive NFTs, double XP weekends, and exclusive $COOKIE rewards. Let it snow! #WinterFest', '{"hasImages": true, "imageCount": 2, "imageTypes": ["winter_event_banner", "holiday_games"]}', '{"likes": 1456, "retweets": 389, "replies": 234, "views": 14560, "engagementRate": 14.3}', 87.5, NOW() - INTERVAL '42 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "seasonal_event"}', NOW() - INTERVAL '41 days'),

('cookie.fun', 'cookie_044_hash', 'Performance optimization: Loading times reduced by 75%! ⚡ New caching system ensures smooth gameplay even on older devices. Everyone deserves great gaming! #Performance', NULL, '{"likes": 823, "retweets": 234, "replies": 123, "views": 8230, "engagementRate": 14.4}', 84.2, NOW() - INTERVAL '43 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "performance_update"}', NOW() - INTERVAL '42 days'),

('cookie.fun', 'cookie_045_hash', 'Mental health awareness: Cookie.fun promotes healthy gaming habits! 🧠 Built-in break reminders, wellness tips, and mental health resources. Your wellbeing matters! #HealthyGaming', '{"hasImages": true, "imageCount": 1, "imageTypes": ["wellness_features"]}', '{"likes": 1567, "retweets": 423, "replies": 189, "views": 15670, "engagementRate": 14.0}', 86.8, NOW() - INTERVAL '44 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "mental_health"}', NOW() - INTERVAL '43 days'),

('cookie.fun', 'cookie_046_hash', 'Creator economy: Fan-made content now earns $COOKIE rewards! 🎨 Art, music, mods, guides - if the community loves it, creators get paid. Support your favorite artists! #CreatorEconomy', NULL, '{"likes": 1234, "retweets": 356, "replies": 145, "views": 12340, "engagementRate": 14.1}', 88.3, NOW() - INTERVAL '45 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "creator_economy"}', NOW() - INTERVAL '44 days'),

('cookie.fun', 'cookie_047_hash', 'Youth program launch: Teaching kids aged 8-16 about responsible gaming and digital citizenship! 👦👧 Next generation deserves proper gaming education. #YouthProgram', '{"hasImages": true, "imageCount": 1, "imageTypes": ["youth_program_poster"]}', '{"likes": 987, "retweets": 267, "replies": 134, "views": 9870, "engagementRate": 14.0}', 85.6, NOW() - INTERVAL '46 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "youth_program"}', NOW() - INTERVAL '45 days'),

('cookie.fun', 'cookie_048_hash', 'Data privacy first: Cookie.fun achieves GDPR and CCPA compliance! 🔒 Your gaming data belongs to you. Transparent policies, user control, zero surveillance. Privacy is not negotiable! #Privacy', NULL, '{"likes": 756, "retweets": 189, "replies": 89, "views": 7560, "engagementRate": 13.7}', 83.1, NOW() - INTERVAL '47 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "privacy_compliance"}', NOW() - INTERVAL '46 days'),

('cookie.fun', 'cookie_049_hash', 'Community voting: Which game genre should we prioritize next? 🗳️ A) Racing games B) Puzzle adventures C) Strategy MMO D) Rhythm games. Vote closes in 48h! #CommunityChoice', '{"hasImages": true, "imageCount": 1, "imageTypes": ["voting_poll_graphic"]}', '{"likes": 1345, "retweets": 378, "replies": 456, "views": 13450, "engagementRate": 16.2}', 84.7, NOW() - INTERVAL '48 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "community_voting"}', NOW() - INTERVAL '47 days'),

('cookie.fun', 'cookie_050_hash', 'Year in review: Cookie.fun 2023 highlights! 📊 - 1M+ players joined - $2.3M distributed in rewards - 50+ games launched - 25+ partnerships formed. 2024 will be even bigger! #YearInReview', '{"hasImages": true, "imageCount": 2, "imageTypes": ["year_stats", "achievement_collage"]}', '{"likes": 2890, "retweets": 712, "replies": 367, "views": 28900, "engagementRate": 14.2}', 95.8, NOW() - INTERVAL '49 days', '{"campaignId": "cookie_gaming_rev_001", "platform": "twitter", "contentType": "year_review"}', NOW() - INTERVAL '48 days'),

-- Yaps.kaito.ai Training Data (50 records)
('yaps.kaito.ai', 'kaito_001_hash', 'AI-powered market prediction: $BTC likely to test $48k resistance within 72 hours based on on-chain metrics and sentiment analysis. 🤖 #AI #Crypto #KaitoAI', '{"hasImages": true, "imageCount": 1, "imageTypes": ["chart"]}', '{"likes": 1567, "retweets": 389, "replies": 123, "views": 15670, "engagementRate": 13.2}', 91.8, NOW() - INTERVAL '6 hours', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "ai_prediction"}', NOW() - INTERVAL '5 hours'),

('yaps.kaito.ai', 'kaito_002_hash', 'Thread: How AI is revolutionizing crypto trading 🧵 1/12 Traditional TA is becoming obsolete. Machine learning models can process thousands of data points simultaneously, identifying patterns humans miss entirely.', NULL, '{"likes": 2234, "retweets": 556, "replies": 178, "views": 22340, "engagementRate": 13.1}', 93.5, NOW() - INTERVAL '1 day', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "educational_thread"}', NOW() - INTERVAL '23 hours'),

('yaps.kaito.ai', 'kaito_003_hash', 'KAITO AI Alert 🚨 Unusual whale activity detected in $ETH. Large accumulation pattern suggests potential breakout. Algorithm confidence: 87% 📊', '{"hasImages": true, "imageCount": 2, "imageTypes": ["chart", "heatmap"]}', '{"likes": 1890, "retweets": 445, "replies": 89, "views": 18900, "engagementRate": 12.8}', 88.7, NOW() - INTERVAL '2 days', '{"campaignId": "yaps_market_analysis_002", "platform": "twitter", "contentType": "whale_alert"}', NOW() - INTERVAL '1 day 22 hours'),

('yaps.kaito.ai', 'kaito_004_hash', 'The future of DeFi is AI-managed liquidity pools. Imagine yield farming that automatically optimizes for maximum returns while managing risk. @KaitoAI is building this reality 🔮', NULL, '{"likes": 1123, "retweets": 267, "replies": 78, "views": 11230, "engagementRate": 12.2}', 86.4, NOW() - INTERVAL '3 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "future_prediction"}', NOW() - INTERVAL '2 days 21 hours'),

('yaps.kaito.ai', 'kaito_005_hash', 'Market sentiment analysis 📈 Bull market signals: - Social mentions up 340% - Fear & Greed index at 75 - Institutional buying increasing - AI models show 78% bull probability #BullMarket', '{"hasImages": true, "imageCount": 1, "imageTypes": ["sentiment_chart"]}', '{"likes": 1456, "retweets": 334, "replies": 112, "views": 14560, "engagementRate": 13.0}', 89.1, NOW() - INTERVAL '4 days', '{"campaignId": "yaps_market_analysis_002", "platform": "twitter", "contentType": "sentiment_analysis"}', NOW() - INTERVAL '3 days 20 hours'),

('yaps.kaito.ai', 'kaito_006_hash', 'New AI trading algo just dropped! 🚀 $BTC prediction model accuracy at 94% - because one algorithm wasn''t enough! Already showing 300% gains potential 🦍 #KaitoAI #AITrading #ToTheMoon', '{"hasImages": true, "imageCount": 1, "imageTypes": ["algo_demo"]}', '{"likes": 2345, "retweets": 567, "replies": 234, "views": 23450, "engagementRate": 13.4}', 79.3, NOW() - INTERVAL '5 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "algo_launch"}', NOW() - INTERVAL '4 days 19 hours'),

('yaps.kaito.ai', 'kaito_007_hash', 'AI trading season is BACK! 🎭 Kaito.ai has created more profitable traders this week than any other platform. The algorithmic energy is unmatched 💎🙌 #AIMode #KaitoAI', NULL, '{"likes": 1567, "retweets": 389, "replies": 156, "views": 15670, "engagementRate": 13.5}', 77.8, NOW() - INTERVAL '6 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "ai_hype"}', NOW() - INTERVAL '5 days 18 hours'),

('yaps.kaito.ai', 'kaito_008_hash', 'POV: You deployed the AI trading bot at launch and now you''re explaining to your wife why there''s a Lambo in the driveway 🏎️ #KaitoAI #AITrading #AlgoLife', '{"hasImages": true, "imageCount": 1, "imageTypes": ["meme_gif"]}', '{"likes": 3456, "retweets": 789, "replies": 345, "views": 34560, "engagementRate": 13.3}', 82.1, NOW() - INTERVAL '7 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "lifestyle_meme"}', NOW() - INTERVAL '6 days 17 hours'),

('yaps.kaito.ai', 'kaito_009_hash', 'Just deployed my first AI trading agent on @KaitoAI! 🤖 This little guy analyzes crypto trends and executes trades automatically. The future of trading is HERE! #AI #KaitoAI #AutoTrading', '{"hasImages": true, "imageCount": 1, "imageTypes": ["agent_demo"]}', '{"likes": 1890, "retweets": 445, "replies": 123, "views": 18900, "engagementRate": 13.1}', 94.7, NOW() - INTERVAL '8 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "agent_showcase"}', NOW() - INTERVAL '7 days 16 hours'),

('yaps.kaito.ai', 'kaito_010_hash', '$KAITO token utility is insane! 🔥 Stake to access premium AI trading models, burn for priority execution, earn through successful predictions. This is how you build a real AI ecosystem! #KAITO #AI', NULL, '{"likes": 1456, "retweets": 334, "replies": 89, "views": 14560, "engagementRate": 12.9}', 91.8, NOW() - INTERVAL '9 days', '{"campaignId": "yaps_market_analysis_002", "platform": "twitter", "contentType": "utility_explanation"}', NOW() - INTERVAL '8 days 15 hours'),

('yaps.kaito.ai', 'kaito_011_hash', 'Deep learning breakthrough: Our neural networks now process 10TB of market data per second! 🧠 Pattern recognition capabilities improved by 400%. The AI trading revolution accelerates!', '{"hasImages": true, "imageCount": 2, "imageTypes": ["neural_network_viz", "performance_metrics"]}', '{"likes": 1789, "retweets": 423, "replies": 156, "views": 17890, "engagementRate": 13.3}', 92.4, NOW() - INTERVAL '10 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "technical_breakthrough"}', NOW() - INTERVAL '9 days 14 hours'),

('yaps.kaito.ai', 'kaito_012_hash', 'Market anomaly detected! 🔍 AI systems identified unusual correlation between solar flare activity and $BTC price movements. Sometimes truth is stranger than fiction! #MarketAnomaly', NULL, '{"likes": 1234, "retweets": 345, "replies": 234, "views": 12340, "engagementRate": 14.8}', 85.7, NOW() - INTERVAL '11 days', '{"campaignId": "yaps_market_analysis_002", "platform": "twitter", "contentType": "anomaly_detection"}', NOW() - INTERVAL '10 days 13 hours'),

('yaps.kaito.ai', 'kaito_013_hash', 'Partnership alert: Kaito.ai x major hedge fund collaboration! 🤝 Institutional-grade AI trading infrastructure now available to retail investors. Democratizing Wall Street tech! #Partnership', '{"hasImages": true, "imageCount": 1, "imageTypes": ["partnership_announcement"]}', '{"likes": 2156, "retweets": 534, "replies": 189, "views": 21560, "engagementRate": 13.4}', 93.8, NOW() - INTERVAL '12 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "partnership_news"}', NOW() - INTERVAL '11 days 12 hours'),

('yaps.kaito.ai', 'kaito_014_hash', 'Risk management 2.0: AI-powered portfolio protection saved users $50M during last week''s volatility! 🛡️ Smart algorithms, smarter protection. Your capital preservation matters! #RiskManagement', NULL, '{"likes": 1567, "retweets": 389, "replies": 123, "views": 15670, "engagementRate": 13.2}', 89.6, NOW() - INTERVAL '13 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "risk_management"}', NOW() - INTERVAL '12 days 11 hours'),

('yaps.kaito.ai', 'kaito_015_hash', 'Academic collaboration: Kaito.ai partners with MIT for quantum-classical hybrid trading algorithms! 🎓 Next-generation AI meets quantum computing. The future is quantum! #QuantumAI', '{"hasImages": true, "imageCount": 2, "imageTypes": ["mit_collaboration", "quantum_computer"]}', '{"likes": 1345, "retweets": 378, "replies": 167, "views": 13450, "engagementRate": 14.2}', 91.2, NOW() - INTERVAL '14 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "academic_partnership"}', NOW() - INTERVAL '13 days 10 hours'),

('yaps.kaito.ai', 'kaito_016_hash', 'Real-time sentiment mining: Our AI now analyzes 1M+ social posts per minute for market sentiment! 📱 Reddit, Twitter, Discord, Telegram - nothing escapes our sentiment radar! #SentimentAnalysis', NULL, '{"likes": 987, "retweets": 267, "replies": 134, "views": 9870, "engagementRate": 14.1}', 87.3, NOW() - INTERVAL '15 days', '{"campaignId": "yaps_market_analysis_002", "platform": "twitter", "contentType": "sentiment_mining"}', NOW() - INTERVAL '14 days 9 hours'),

('yaps.kaito.ai', 'kaito_017_hash', 'Cross-chain intelligence: Kaito.ai now tracks and predicts across 15 different blockchains simultaneously! ⛓️ True multi-chain AI for the multi-chain future! #CrossChain', '{"hasImages": true, "imageCount": 1, "imageTypes": ["multichain_dashboard"]}', '{"likes": 1456, "retweets": 334, "replies": 145, "views": 14560, "engagementRate": 13.7}', 88.9, NOW() - INTERVAL '16 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "multichain_feature"}', NOW() - INTERVAL '15 days 8 hours'),

('yaps.kaito.ai', 'kaito_018_hash', 'User milestone: AI trading bots managed $1B in trading volume this month! 💰 From zero to billion in 18 months. Trust through technology, results through intelligence! #Milestone', NULL, '{"likes": 2789, "retweets": 678, "replies": 234, "views": 27890, "engagementRate": 13.3}', 95.4, NOW() - INTERVAL '17 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "volume_milestone"}', NOW() - INTERVAL '16 days 7 hours'),

('yaps.kaito.ai', 'kaito_019_hash', 'Educational series: "AI Trading 101" - How neural networks identify support and resistance levels 📚 Free masterclass series for the community. Knowledge should be accessible! #Education', '{"hasImages": true, "imageCount": 1, "imageTypes": ["educational_series_poster"]}', '{"likes": 1234, "retweets": 345, "replies": 189, "views": 12340, "engagementRate": 14.3}', 86.7, NOW() - INTERVAL '18 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "education_series"}', NOW() - INTERVAL '17 days 6 hours'),

('yaps.kaito.ai', 'kaito_020_hash', 'Regulatory compliance: Kaito.ai achieves SOC 2 Type II certification! ✅ Enterprise-grade security for institutional adoption. Trust through transparency! #Compliance', NULL, '{"likes": 789, "retweets": 189, "replies": 89, "views": 7890, "engagementRate": 13.8}', 84.1, NOW() - INTERVAL '19 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "compliance_news"}', NOW() - INTERVAL '18 days 5 hours'),

('yaps.kaito.ai', 'kaito_021_hash', 'Innovation lab: Experimenting with AI-powered NFT valuation models! 🎨 Machine learning meets digital art. Can AI predict the next Bored Ape? Research ongoing! #NFTValuation', '{"hasImages": true, "imageCount": 2, "imageTypes": ["nft_analysis_ui", "valuation_models"]}', '{"likes": 1567, "retweets": 423, "replies": 178, "views": 15670, "engagementRate": 13.9}', 89.5, NOW() - INTERVAL '20 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "nft_research"}', NOW() - INTERVAL '19 days 4 hours'),

('yaps.kaito.ai', 'kaito_022_hash', 'Performance report: AI models achieved 89% prediction accuracy this quarter! 📊 Consistent performance through bull and bear markets. Algorithm stability is our strength! #Performance', NULL, '{"likes": 1345, "retweets": 356, "replies": 123, "views": 13450, "engagementRate": 13.6}', 91.7, NOW() - INTERVAL '21 days', '{"campaignId": "yaps_market_analysis_002", "platform": "twitter", "contentType": "performance_report"}', NOW() - INTERVAL '20 days 3 hours'),

('yaps.kaito.ai', 'kaito_023_hash', 'Community spotlight: Meet Dr. Sarah Chen, data scientist who created the winning trading strategy in our AI competition! 🏆 $10k prize + strategy implementation. Brilliance rewarded! #Community', '{"hasImages": true, "imageCount": 1, "imageTypes": ["winner_spotlight"]}', '{"likes": 987, "retweets": 245, "replies": 134, "views": 9870, "engagementRate": 13.8}', 85.9, NOW() - INTERVAL '22 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "community_spotlight"}', NOW() - INTERVAL '21 days 2 hours'),

('yaps.kaito.ai', 'kaito_024_hash', 'Technical deep dive: How transformers architecture revolutionized our price prediction models! 🤖 Attention mechanisms applied to financial markets. The math behind the magic! #TechnicalDeepDive', NULL, '{"likes": 756, "retweets": 178, "replies": 89, "views": 7560, "engagementRate": 13.5}', 88.2, NOW() - INTERVAL '23 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "technical_analysis"}', NOW() - INTERVAL '22 days 1 hour'),

('yaps.kaito.ai', 'kaito_025_hash', 'API update: Developers can now access real-time AI predictions via our RESTful API! 🔧 Build your own trading apps with Kaito.ai intelligence. Innovation through integration! #APIUpdate', '{"hasImages": true, "imageCount": 1, "imageTypes": ["api_documentation"]}', '{"likes": 1123, "retweets": 289, "replies": 145, "views": 11230, "engagementRate": 13.9}', 87.8, NOW() - INTERVAL '24 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "api_release"}', NOW() - INTERVAL '23 days'),

-- Additional Yaps.kaito.ai content (25 more records)
('yaps.kaito.ai', 'kaito_026_hash', 'Market regime detection: Our AI identified we''re entering a new market phase 72 hours before traditional indicators! 🎯 Regime-aware algorithms adapt to changing conditions. #MarketRegime', NULL, '{"likes": 1456, "retweets": 378, "replies": 167, "views": 14560, "engagementRate": 13.8}', 90.3, NOW() - INTERVAL '25 days', '{"campaignId": "yaps_market_analysis_002", "platform": "twitter", "contentType": "regime_detection"}', NOW() - INTERVAL '24 days'),

('yaps.kaito.ai', 'kaito_027_hash', 'Institutional adoption: Major pension fund deploys $100M through Kaito.ai algorithms! 🏛️ AI trading solutions trusted by the most conservative investors. Institutional validation! #Institutional', '{"hasImages": true, "imageCount": 1, "imageTypes": ["institutional_announcement"]}', '{"likes": 2234, "retweets": 556, "replies": 234, "views": 22340, "engagementRate": 13.5}', 94.1, NOW() - INTERVAL '26 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "institutional_news"}', NOW() - INTERVAL '25 days'),

('yaps.kaito.ai', 'kaito_028_hash', 'Explainable AI: New dashboard shows exactly why our algorithms made each trade decision! 🔍 Black box no more - full transparency for confident trading. Trust through understanding! #ExplainableAI', NULL, '{"likes": 1567, "retweets": 389, "replies": 156, "views": 15670, "engagementRate": 13.5}', 88.7, NOW() - INTERVAL '27 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "explainable_ai"}', NOW() - INTERVAL '26 days'),

('yaps.kaito.ai', 'kaito_029_hash', 'Research breakthrough: AI discovers new correlation between macro economics and crypto markets! 📈 Fed policy decisions now integrated into prediction models. Macro meets crypto! #MacroAnalysis', '{"hasImages": true, "imageCount": 2, "imageTypes": ["correlation_chart", "macro_indicators"]}', '{"likes": 1789, "retweets": 445, "replies": 178, "views": 17890, "engagementRate": 13.7}', 91.9, NOW() - INTERVAL '28 days', '{"campaignId": "yaps_market_analysis_002", "platform": "twitter", "contentType": "macro_research"}', NOW() - INTERVAL '27 days'),

('yaps.kaito.ai', 'kaito_030_hash', 'Global expansion: Kaito.ai now supports 50+ international exchanges! 🌍 Trade globally, think locally. AI algorithms adapted for regional market characteristics! #GlobalExpansion', NULL, '{"likes": 1345, "retweets": 334, "replies": 145, "views": 13450, "engagementRate": 13.8}', 89.2, NOW() - INTERVAL '29 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "global_expansion"}', NOW() - INTERVAL '28 days'),

('yaps.kaito.ai', 'kaito_031_hash', 'Sustainability initiative: Kaito.ai achieves carbon-neutral AI training! 🌱 Green algorithms for a green future. Responsible AI development starts with environmental consciousness! #GreenAI', '{"hasImages": true, "imageCount": 1, "imageTypes": ["sustainability_report"]}', '{"likes": 987, "retweets": 234, "replies": 123, "views": 9870, "engagementRate": 13.6}', 86.4, NOW() - INTERVAL '30 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "sustainability"}', NOW() - INTERVAL '29 days'),

('yaps.kaito.ai', 'kaito_032_hash', 'AI ethics board established: Ensuring responsible AI development in financial markets! ⚖️ Ethics-first approach to algorithmic trading. Technology serves humanity, not the reverse! #AIEthics', NULL, '{"likes": 756, "retweets": 178, "replies": 89, "views": 7560, "engagementRate": 13.5}', 84.8, NOW() - INTERVAL '31 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "ai_ethics"}', NOW() - INTERVAL '30 days'),

('yaps.kaito.ai', 'kaito_033_hash', 'Real-time arbitrage: AI identifies and executes cross-exchange opportunities in microseconds! ⚡ Speed of light trading with nanosecond precision. The future of arbitrage is here! #Arbitrage', '{"hasImages": true, "imageCount": 1, "imageTypes": ["arbitrage_visualization"]}', '{"likes": 1234, "retweets": 345, "replies": 167, "views": 12340, "engagementRate": 14.1}', 89.7, NOW() - INTERVAL '32 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "arbitrage_feature"}', NOW() - INTERVAL '31 days'),

('yaps.kaito.ai', 'kaito_034_hash', 'Academic publication: Kaito.ai research team publishes in Nature Machine Intelligence! 📚 "Deep Learning Applications in Cryptocurrency Market Prediction" - peer-reviewed excellence! #Research', NULL, '{"likes": 1123, "retweets": 289, "replies": 134, "views": 11230, "engagementRate": 13.8}', 92.5, NOW() - INTERVAL '33 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "academic_publication"}', NOW() - INTERVAL '32 days'),

('yaps.kaito.ai', 'kaito_035_hash', 'User testimonial: "Kaito.ai algorithms helped me achieve 340% returns while I focused on my day job!" - Maria, Software Engineer. Passive income through active AI! #Testimonial', '{"hasImages": true, "imageCount": 1, "imageTypes": ["user_testimonial"]}', '{"likes": 1567, "retweets": 423, "replies": 189, "views": 15670, "engagementRate": 14.0}', 87.6, NOW() - INTERVAL '34 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "user_testimonial"}', NOW() - INTERVAL '33 days'),

('yaps.kaito.ai', 'kaito_036_hash', 'Security audit completed: Zero vulnerabilities found in Kaito.ai smart contracts! 🔒 CertiK, Trail of Bits, and Quantstamp all give clean reports. Your funds are fortress-protected! #Security', NULL, '{"likes": 892, "retweets": 234, "replies": 123, "views": 8920, "engagementRate": 14.0}', 85.3, NOW() - INTERVAL '35 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "security_audit"}', NOW() - INTERVAL '34 days'),

('yaps.kaito.ai', 'kaito_037_hash', 'Machine learning fairness: Ensuring AI algorithms provide equal opportunities across all user demographics! 🤝 Bias-free AI for inclusive financial markets. Fairness is not optional! #MLFairness', '{"hasImages": true, "imageCount": 1, "imageTypes": ["fairness_metrics"]}', '{"likes": 678, "retweets": 156, "replies": 89, "views": 6780, "engagementRate": 13.6}', 83.7, NOW() - INTERVAL '36 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "ml_fairness"}', NOW() - INTERVAL '35 days'),

('yaps.kaito.ai', 'kaito_038_hash', 'Quantum resistance: Preparing Kaito.ai infrastructure for the post-quantum era! 🔮 Quantum-safe cryptography ensures long-term security. Future-proofing starts today! #QuantumResistance', NULL, '{"likes": 1234, "retweets": 345, "replies": 156, "views": 12340, "engagementRate": 14.1}', 88.9, NOW() - INTERVAL '37 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "quantum_resistance"}', NOW() - INTERVAL '36 days'),

('yaps.kaito.ai', 'kaito_039_hash', 'Edge computing deployment: AI models now run closer to exchanges for ultra-low latency! 🚀 Milliseconds matter in trading. Geographic distribution for speed optimization! #EdgeComputing', '{"hasImages": true, "imageCount": 1, "imageTypes": ["edge_network_map"]}', '{"likes": 987, "retweets": 267, "replies": 134, "views": 9870, "engagementRate": 14.1}', 86.8, NOW() - INTERVAL '38 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "edge_computing"}', NOW() - INTERVAL '37 days'),

('yaps.kaito.ai', 'kaito_040_hash', 'Community governance: $KAITO holders vote on algorithm updates! 🗳️ Democratic AI development where users shape the future. Your tokens, your voice, your algorithms! #CommunityGovernance', NULL, '{"likes": 1456, "retweets": 389, "replies": 234, "views": 14560, "engagementRate": 14.4}', 88.1, NOW() - INTERVAL '39 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "community_governance"}', NOW() - INTERVAL '38 days'),

('yaps.kaito.ai', 'kaito_041_hash', 'Disaster recovery: Kaito.ai systems survive simulated cyber-attack with 99.9% uptime! 💪 Military-grade resilience for financial infrastructure. Your trading never stops! #DisasterRecovery', '{"hasImages": true, "imageCount": 1, "imageTypes": ["resilience_test_results"]}', '{"likes": 823, "retweets": 198, "replies": 89, "views": 8230, "engagementRate": 13.5}', 84.6, NOW() - INTERVAL '40 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "disaster_recovery"}', NOW() - INTERVAL '39 days'),

('yaps.kaito.ai', 'kaito_042_hash', 'Innovation award: Kaito.ai wins "Best AI Application in Finance" at FinTech Global Awards! 🏆 Industry recognition for technological excellence. Innovation acknowledged by peers! #Award', NULL, '{"likes": 1789, "retweets": 456, "replies": 189, "views": 17890, "engagementRate": 13.6}', 91.4, NOW() - INTERVAL '41 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "industry_award"}', NOW() - INTERVAL '40 days'),

('yaps.kaito.ai', 'kaito_043_hash', 'Mobile optimization: Kaito.ai algorithms now optimized for smartphone trading! 📱 Full AI power in your pocket. Professional trading infrastructure, mobile convenience! #MobileOptimization', '{"hasImages": true, "imageCount": 2, "imageTypes": ["mobile_interface", "performance_comparison"]}', '{"likes": 1234, "retweets": 334, "replies": 145, "views": 12340, "engagementRate": 13.9}', 87.2, NOW() - INTERVAL '42 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "mobile_optimization"}', NOW() - INTERVAL '41 days'),

('yaps.kaito.ai', 'kaito_044_hash', 'Predictive maintenance: AI systems predict and prevent their own failures! 🔧 Self-healing infrastructure ensures maximum uptime. Machines maintaining machines for human benefit! #PredictiveMaintenance', NULL, '{"likes": 756, "retweets": 189, "replies": 89, "views": 7560, "engagementRate": 13.7}', 85.9, NOW() - INTERVAL '43 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "predictive_maintenance"}', NOW() - INTERVAL '42 days'),

('yaps.kaito.ai', 'kaito_045_hash', 'Open source contribution: Kaito.ai releases non-commercial research tools to academic community! 🎓 Advancing AI research for everyone. Knowledge sharing accelerates innovation! #OpenSource', '{"hasImages": true, "imageCount": 1, "imageTypes": ["open_source_tools"]}', '{"likes": 1123, "retweets": 289, "replies": 167, "views": 11230, "engagementRate": 14.0}', 88.6, NOW() - INTERVAL '44 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "open_source"}', NOW() - INTERVAL '43 days'),

('yaps.kaito.ai', 'kaito_046_hash', 'Language support: Kaito.ai interface now available in 25+ languages! 🌍 AI trading for the global community. Breaking language barriers in financial technology! #GlobalLanguageSupport', NULL, '{"likes": 987, "retweets": 245, "replies": 123, "views": 9870, "engagementRate": 13.7}', 86.3, NOW() - INTERVAL '45 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "language_support"}', NOW() - INTERVAL '44 days'),

('yaps.kaito.ai', 'kaito_047_hash', 'Mentorship program: Experienced traders mentor newcomers using Kaito.ai tools! 👥 Knowledge transfer in the age of AI. Learning together, growing together! #MentorshipProgram', '{"hasImages": true, "imageCount": 1, "imageTypes": ["mentorship_program"]}', '{"likes": 1345, "retweets": 356, "replies": 178, "views": 13450, "engagementRate": 14.1}', 87.8, NOW() - INTERVAL '46 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "mentorship_program"}', NOW() - INTERVAL '45 days'),

('yaps.kaito.ai', 'kaito_048_hash', 'Economic research: Kaito.ai algorithms help economists study market efficiency! 📊 AI tools advancing academic understanding of financial markets. Technology serving science! #EconomicResearch', NULL, '{"likes": 678, "retweets": 156, "replies": 89, "views": 6780, "engagementRate": 13.6}', 84.2, NOW() - INTERVAL '47 days', '{"campaignId": "yaps_market_analysis_002", "platform": "twitter", "contentType": "economic_research"}', NOW() - INTERVAL '46 days'),

('yaps.kaito.ai', 'kaito_049_hash', 'Future vision: Kaito.ai roadmap for 2025-2030! 🛣️ Quantum algorithms, brain-computer interfaces, universal market intelligence. The future of AI trading starts now! #FutureVision', '{"hasImages": true, "imageCount": 2, "imageTypes": ["roadmap_timeline", "future_concepts"]}', '{"likes": 2156, "retweets": 567, "replies": 289, "views": 21560, "engagementRate": 14.2}', 93.7, NOW() - INTERVAL '48 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "future_roadmap"}', NOW() - INTERVAL '47 days'),

('yaps.kaito.ai', 'kaito_050_hash', 'Anniversary celebration: 2 years of Kaito.ai revolutionizing crypto trading! 🎉 From startup to industry leader. Thank you to our amazing community for this incredible journey! #Anniversary', '{"hasImages": true, "imageCount": 2, "imageTypes": ["anniversary_collage", "milestone_achievements"]}', '{"likes": 3456, "retweets": 823, "replies": 456, "views": 34560, "engagementRate": 14.0}', 96.8, NOW() - INTERVAL '49 days', '{"campaignId": "yaps_ai_crypto_fusion_001", "platform": "twitter", "contentType": "anniversary_celebration"}', NOW() - INTERVAL '48 days');

-- Update sequence for mindshare_training_data table if using PostgreSQL
SELECT setval('mindshare_training_data_id_seq', (SELECT MAX(id) FROM mindshare_training_data));

-- Add indexes for better performance
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_mindshare_platform_scraped 
ON mindshare_training_data("platformSource", "scrapedAt" DESC);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_mindshare_score_desc 
ON mindshare_training_data("mindshareScore" DESC);

-- Success message
DO $$
BEGIN
    RAISE NOTICE 'Successfully seeded % mindshare training records from platforms: cookie.fun, yaps.kaito.ai', 
    (SELECT COUNT(*) FROM mindshare_training_data WHERE "platformSource" IN ('cookie.fun', 'yaps.kaito.ai'));
END $$; 