// Tile images for Hero floating tiles and DiscoverPreview (from wander-discover-connect)
export const tileImages = [
  "/landing/discover-1.jpg",
  "/landing/discover-2.jpg",
  "/landing/discover-3.jpg",
  "/landing/discover-4.jpg",
  "/landing/discover-5.jpg",
  "/landing/discover-6.jpg",
  "/landing/discover-7.jpg",
  "/landing/discover-8.jpg",
  "/landing/discover-9.jpg",
  "/landing/discover-10.jpg",
  "/landing/discover-11.jpg",
  "/landing/discover-12.jpg",
  "/landing/discover-13.jpg",
  "/landing/discover-14.jpg",
  "/landing/discover-15.jpg",
  "/landing/discover-16.jpg",
  "/landing/discover-17.jpg",
  "/landing/discover-18.jpg",
];
