import os

from xai_sdk import Client
from xai_sdk.chat import user, image

client = Client(api_key=os.getenv('XAI_API_KEY'))

image_url = "https://v3b.fal.media/files/b/tiger/PejSOdyEEhVjA9D0KQkxF_be06fa38b58349a98eb58db8a5430584.png"

chat = client.chat.create(model="grok-4")
chat.append(
    user(
        '''Does the image have any anomaly like broken hand, person coming out of car etc.? Think of any other possible anomalies.  
        ignore the effects, shadows, characters etc. since the image is generated by AI only. Image shouldn't have anything wierd
        Give output as json with following keys: anomaly_present (true or false), anomaly_description (if present)''',
        image(image_url=image_url, detail="high"),
    )
)

response = chat.sample()
print(response.content)